In [1]:
import tensorflow as tf

In [2]:
print(tf.reduce_sum(tf.random.normal([1000, 1000])))

tf.Tensor(-227.81746, shape=(), dtype=float32)


In [3]:
import torch
print(f'Tensor: {torch.tensor([10, 10])}')
print(f'PyTorch version: {torch.__version__}')    
print('Succeeded')


Tensor: tensor([10, 10])
PyTorch version: 2.1.0+cpu
Succeeded


# Pytorch

### Calculate the dot product between two vectors each of length 3 

In [11]:
import torch

vector1 = torch.tensor([0.4195, 0.9295, 0.2033])
vector2 = torch.tensor([0.7640, 0.0032, 0.4926])
dot_product = torch.dot(vector1, vector2)

print(" Vector 1:", vector1)
print(" Vector 2:", vector2)
print("Dot Product:", dot_product.item())



 Vector 1: tensor([0.4195, 0.9295, 0.2033])
 Vector 2: tensor([0.7640, 0.0032, 0.4926])
Dot Product: 0.423617959022522


### Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2)

In [12]:
matrix1 = torch.tensor([[0.0333, 0.3678],
        [0.2875, 0.1362]])
matrix2 = torch.tensor([[0.2262, 0.8530],
        [0.2330, 0.7130]])

matrix_product = torch.mm(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\n Matrix 2:")
print(matrix2)
print("\nMatrix Multiplication Result:")
print(matrix_product)


Matrix 1:
tensor([[0.0333, 0.3678],
        [0.2875, 0.1362]])

 Matrix 2:
tensor([[0.2262, 0.8530],
        [0.2330, 0.7130]])

Matrix Multiplication Result:
tensor([[0.0932, 0.2906],
        [0.0968, 0.3423]])


# Tensorflow

### Calculate the dot product between the same vectors as above (re-define them in Tensorflow) 

In [14]:
import tensorflow as tf

vector1_tf = tf.constant([0.4195, 0.9295, 0.2033], dtype=tf.float32)
vector2_tf = tf.constant([0.7640, 0.0032, 0.4926], dtype=tf.float32)

dot_product_tf = tf.tensordot(vector1_tf, vector2_tf, axes=1)

print("Dot Product (TensorFlow):", dot_product_tf.numpy())



Dot Product (TensorFlow): 0.42361796


### Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow) 

In [15]:
matrix1_tf = tf.constant([[0.0333, 0.3678],
        [0.2875, 0.1362]], dtype=tf.float32)
matrix2_tf = tf.constant([[0.2262, 0.8530],
        [0.2330, 0.7130]], dtype=tf.float32)

matrix_product_tf = tf.linalg.matmul(matrix1_tf, matrix2_tf)

print("\nMatrix Multiplication Result (TensorFlow):")
print(matrix_product_tf.numpy())



Matrix Multiplication Result (TensorFlow):
[[0.09322986 0.29064628]
 [0.0967671  0.34234807]]
